scraper:
  links: 
    - https://www.youtube.com/watch?v=DkS1pkKpILY
    - https://www.youtube.com/watch?v=gXvuJu1kt48

  channel_link: 
  scrape_n_videos_from_channel: 4 # -1 to scrape all 
  raw_data_path: data/raw_data

asr:
  # delete_corrupted_audio: True
  input_path: data/processed_data
  model_type: medium.en
  max_wav_len: 20 # in seconds dels longer wavs

post_processing:
  input_path: data/raw_data
  output_path: data/processed_data
  split_on_silence:
    min_silence_len: 400 # in ms
    keep_silence: True
    silence_thresh: -40